# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8c2YPp4WSGgWmLFnVgCf2zzg9jtebng
"""

class VacuumEnvironment:
    def __init__(self):
        self.rooms = {"A": 1, "B": 1}

    def show(self):
        for room, status in self.rooms.items():
            print(f"Room {room}: {'Dirty' if status else 'Clean'}")


class SimpleReflexAgent:
    def __init__(self):
        self.location = "A"

    def act(self, env):
        if env.rooms[self.location] == 1:
            print(f"Agent at {self.location}: SUCK")
            env.rooms[self.location] = 0
        elif self.location == "A":
            print("Agent at A: MOVE RIGHT")
            self.location = "B"
        else:
            print("Agent at B: MOVE LEFT")
            self.location = "A"


class GoalBasedAgent:
    def __init__(self):
        self.location = "A"

    def goal_achieved(self, env):
        return all(status == 0 for status in env.rooms.values())

    def act(self, env):
        if env.rooms[self.location] == 1:
            print(f"Agent at {self.location}: SUCK")
            env.rooms[self.location] = 0
        elif self.location == "A" and env.rooms["B"] == 1:
            print("Agent at A: MOVE RIGHT")
            self.location = "B"
        elif self.location == "B" and env.rooms["A"] == 1:
            print("Agent at B: MOVE LEFT")
            self.location = "A"


env = VacuumEnvironment()

print("1. Simple Reflex Agent")
print("2. Goal-Based Agent")

choice = input("Enter your choice (1 or 2): ")

print("\nInitial Environment:")
env.show()

if choice == "1":
    agent = SimpleReflexAgent()

    for _ in range(5):
        agent.act(env)

elif choice == "2":
    agent = GoalBasedAgent()

    while not agent.goal_achieved(env):
        agent.act(env)

    print("Goal achieved! All rooms are clean.")

else:
    print("Invalid choice.")

print("\nFinal Environment:")
env.show()

